name: PSMWSL Action Workflows
author: PSM Web Solutions
description: Run a GitHub Action as a GitHub App.
inputs:
  token:
    description: Github token
    required: true
  action:
    description: PSMWSL action to perform
    required: true
runs:
  using: "composite"
  steps:
    - name: Execute the action
      env:
        GH_TOKEN: ${{ inputs.token }}
        ACTION: ${{ inputs.action }}
      shell: bash
      run: |
        php ${{ github.action_path }}/src/class-workflows.php
branding:
  icon: unlock
  color: gray-dark